CREATE INDEX "idx_users_site_id" ON "users" USING btree ("site_id");--> statement-breakpoint
CREATE INDEX "idx_emergency_contacts_employee_id" ON "emergency_contacts" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX "idx_employees_cost_centre_id" ON "employees" USING btree ("cost_centre_id");--> statement-breakpoint
CREATE INDEX "idx_daily_record_photos_daily_record_id" ON "daily_record_photos" USING btree ("daily_record_id");--> statement-breakpoint
CREATE INDEX "idx_feed_distributions_production_batch_id" ON "feed_distributions" USING btree ("production_batch_id");--> statement-breakpoint
CREATE INDEX "idx_feed_inventory_supplier_id" ON "feed_inventory" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "idx_feed_production_materials_production_batch_id" ON "feed_production_materials" USING btree ("production_batch_id");--> statement-breakpoint
CREATE INDEX "idx_feed_production_materials_inventory_item_id" ON "feed_production_materials" USING btree ("inventory_item_id");--> statement-breakpoint
CREATE INDEX "idx_feed_recipe_ingredients_recipe_id" ON "feed_recipe_ingredients" USING btree ("recipe_id");--> statement-breakpoint
CREATE INDEX "idx_feed_recipe_ingredients_inventory_item_id" ON "feed_recipe_ingredients" USING btree ("inventory_item_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_lots_purchase_order_item_id" ON "inventory_lots" USING btree ("purchase_order_item_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_movements_purchase_order_id" ON "inventory_movements" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_movements_production_batch_id" ON "inventory_movements" USING btree ("production_batch_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_cost_centre_id" ON "purchase_orders" USING btree ("cost_centre_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_requisitions_purchase_order_id" ON "purchase_requisitions" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX "idx_stock_transfer_lines_source_lot_id" ON "stock_transfer_lines" USING btree ("source_lot_id");--> statement-breakpoint
CREATE INDEX "idx_stock_transfer_lines_inventory_item_id" ON "stock_transfer_lines" USING btree ("inventory_item_id");--> statement-breakpoint
CREATE INDEX "idx_stock_transfers_from_location_id" ON "stock_transfers" USING btree ("from_location_id");--> statement-breakpoint
CREATE INDEX "idx_stock_transfers_to_location_id" ON "stock_transfers" USING btree ("to_location_id");--> statement-breakpoint
CREATE INDEX "idx_supplier_payments_treasury_transaction_id" ON "supplier_payments" USING btree ("treasury_transaction_id");--> statement-breakpoint
CREATE INDEX "idx_supplier_payments_finance_account_id" ON "supplier_payments" USING btree ("finance_account_id");--> statement-breakpoint
CREATE INDEX "idx_buyer_receipt_lines_treasury_transaction_id" ON "buyer_receipt_lines" USING btree ("treasury_transaction_id");--> statement-breakpoint
CREATE INDEX "idx_buyer_receipt_lines_finance_account_id" ON "buyer_receipt_lines" USING btree ("finance_account_id");--> statement-breakpoint
CREATE INDEX "idx_sale_bookings_batch_id" ON "sale_bookings" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_sale_bookings_buyer_id" ON "sale_bookings" USING btree ("buyer_id");--> statement-breakpoint
CREATE INDEX "idx_sale_bookings_sale_id" ON "sale_bookings" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "idx_sales_site_id" ON "sales" USING btree ("site_id");--> statement-breakpoint
CREATE INDEX "idx_payroll_treasury_transaction_id" ON "payroll" USING btree ("treasury_transaction_id");--> statement-breakpoint
CREATE INDEX "idx_payroll_allowances_payroll_id" ON "payroll_allowances" USING btree ("payroll_id");--> statement-breakpoint
CREATE INDEX "idx_payroll_deductions_payroll_id" ON "payroll_deductions" USING btree ("payroll_id");--> statement-breakpoint
CREATE INDEX "idx_staff_loans_treasury_transaction_id" ON "staff_loans" USING btree ("treasury_transaction_id");--> statement-breakpoint
CREATE INDEX "idx_operational_expenses_treasury_transaction_id" ON "operational_expenses" USING btree ("treasury_transaction_id");--> statement-breakpoint
CREATE INDEX "idx_operational_expenses_cost_centre_id" ON "operational_expenses" USING btree ("cost_centre_id");--> statement-breakpoint
CREATE INDEX "idx_petty_cash_expenses_cost_centre_id" ON "petty_cash_expenses" USING btree ("cost_centre_id");--> statement-breakpoint
CREATE INDEX "idx_house_turnarounds_previous_batch_id" ON "house_turnarounds" USING btree ("previous_batch_id");